# Variables
@baseUrl = http://localhost:3333/api

###

GET {{baseUrl}}/health
content-type: application/json

###

POST {{baseUrl}}/signup
content-type: application/json

{
    "name": "Higor",
    "email": "higor@email.com",
    "password": "123456789"
}

###

POST {{baseUrl}}/signin
content-type: application/json

{
    "email": "higor@email.com",
    "password": "123456789"
}