# Variables
@baseUrl = http://localhost:3333/api
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjg1OTdhNi03ZjY0LTQxMWUtYjMwMC1mY2UyMzVmOWI3YTUiLCJpYXQiOjE3NTM5ODk4NDYsImV4cCI6MTc1NDU5NDY0Nn0.4pwA0U2wSk3wdrz4SwmSyX9gzE_aqYhCGeT33-3DdqI

###

# @name HealthCheckFromServer
GET {{baseUrl}}/health
content-type: application/json

###

# @name CreateANewUser
POST {{baseUrl}}/signup
content-type: application/json

{
    "name": "Higor Silva",
    "email": "higorsilva@email.com",
    "password": "12345678"
}

###

# @name LogInAUser
POST {{baseUrl}}/signin
content-type: application/json

{
    "email": "higorcode@email.com",
    "password": "12345678"
}

###

# @name GetUserDataFromDashboard
GET {{baseUrl}}/me
content-type: application/json
Authorization: Bearer {{authToken}}