services:
  postgresql:
    image: bitnami/postgresql:17.5.0
    container_name: finance-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=financeapi
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data: