export const ErrorCodes = {
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_MONTH: 'INVALID_MONTH',
  INVALID_YEAR: 'INVALID_YEAR',

  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  PAGE_OUT_OF_RANGE: 'PAGE_OUT_OF_RANGE',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PRIVATE_WORKSPACE_CANNOT_HAVE_MEMBERS:
    'PRIVATE_WORKSPACE_CANNOT_HAVE_MEMBERS',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',

  USER_ALREADY_WORKSPACE_MEMBER: 'USER_ALREADY_WORKSPACE_MEMBER',
  USER_CANNOT_REMOVE_SELF_FROM_WORKSPACE:
    'USER_CANNOT_REMOVE_SELF_FROM_WORKSPACE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_WORKSPACE_MEMBER: 'USER_NOT_WORKSPACE_MEMBER',

  WORKSPACE_CREATION_FAILED: 'WORKSPACE_CREATION_FAILED',
  WORKSPACE_MEMBER_CREATION_FAILED: 'WORKSPACE_MEMBER_CREATION_FAILED',
  WORKSPACE_MEMBER_NOT_FOUND: 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_MEMBER_ROLE_NOT_FOUND: 'WORKSPACE_MEMBER_ROLE_NOT_FOUND',
  WORKSPACE_INVITE_ALREADY_EXISTS: 'WORKSPACE_INVITE_ALREADY_EXISTS',
  WORKSPACE_INVITE_EXPIRED: 'WORKSPACE_INVITE_EXPIRED',
  WORKSPACE_INVITE_NOT_FOUND: 'WORKSPACE_INVITE_NOT_FOUND',
  WORKSPACE_INVITE_SELF_NOT_ALLOWED: 'WORKSPACE_INVITE_SELF_NOT_ALLOWED',
  WORKSPACE_NAME_ALREADY_EXISTS: 'WORKSPACE_NAME_ALREADY_EXISTS',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_OWNER_CANNOT_BE_REMOVED: 'WORKSPACE_OWNER_CANNOT_BE_REMOVED',
  WORKSPACE_OWNER_ROLE_IMMUTABLE: 'WORKSPACE_OWNER_ROLE_IMMUTABLE',
  WORKSPACE_SLUG_REQUIRED: 'WORKSPACE_SLUG_REQUIRED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
